# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/michael/Dropbox/gameboyC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/michael/Dropbox/gameboyC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michael/Dropbox/gameboyC/CMakeFiles /home/michael/Dropbox/gameboyC/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michael/Dropbox/gameboyC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gameboy

# Build rule for target.
gameboy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gameboy
.PHONY : gameboy

# fast build rule for target.
gameboy/fast:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/build
.PHONY : gameboy/fast

src/Common/FileUtils.o: src/Common/FileUtils.cpp.o
.PHONY : src/Common/FileUtils.o

# target to build an object file
src/Common/FileUtils.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Common/FileUtils.cpp.o
.PHONY : src/Common/FileUtils.cpp.o

src/Common/FileUtils.i: src/Common/FileUtils.cpp.i
.PHONY : src/Common/FileUtils.i

# target to preprocess a source file
src/Common/FileUtils.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Common/FileUtils.cpp.i
.PHONY : src/Common/FileUtils.cpp.i

src/Common/FileUtils.s: src/Common/FileUtils.cpp.s
.PHONY : src/Common/FileUtils.s

# target to generate assembly for a file
src/Common/FileUtils.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Common/FileUtils.cpp.s
.PHONY : src/Common/FileUtils.cpp.s

src/Cpu/Z80InstructionSet.o: src/Cpu/Z80InstructionSet.cpp.o
.PHONY : src/Cpu/Z80InstructionSet.o

# target to build an object file
src/Cpu/Z80InstructionSet.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Cpu/Z80InstructionSet.cpp.o
.PHONY : src/Cpu/Z80InstructionSet.cpp.o

src/Cpu/Z80InstructionSet.i: src/Cpu/Z80InstructionSet.cpp.i
.PHONY : src/Cpu/Z80InstructionSet.i

# target to preprocess a source file
src/Cpu/Z80InstructionSet.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Cpu/Z80InstructionSet.cpp.i
.PHONY : src/Cpu/Z80InstructionSet.cpp.i

src/Cpu/Z80InstructionSet.s: src/Cpu/Z80InstructionSet.cpp.s
.PHONY : src/Cpu/Z80InstructionSet.s

# target to generate assembly for a file
src/Cpu/Z80InstructionSet.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Cpu/Z80InstructionSet.cpp.s
.PHONY : src/Cpu/Z80InstructionSet.cpp.s

src/Memory/CartridgeHeader.o: src/Memory/CartridgeHeader.cpp.o
.PHONY : src/Memory/CartridgeHeader.o

# target to build an object file
src/Memory/CartridgeHeader.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/CartridgeHeader.cpp.o
.PHONY : src/Memory/CartridgeHeader.cpp.o

src/Memory/CartridgeHeader.i: src/Memory/CartridgeHeader.cpp.i
.PHONY : src/Memory/CartridgeHeader.i

# target to preprocess a source file
src/Memory/CartridgeHeader.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/CartridgeHeader.cpp.i
.PHONY : src/Memory/CartridgeHeader.cpp.i

src/Memory/CartridgeHeader.s: src/Memory/CartridgeHeader.cpp.s
.PHONY : src/Memory/CartridgeHeader.s

# target to generate assembly for a file
src/Memory/CartridgeHeader.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/CartridgeHeader.cpp.s
.PHONY : src/Memory/CartridgeHeader.cpp.s

src/Memory/Customizers/BasicMemory.o: src/Memory/Customizers/BasicMemory.cpp.o
.PHONY : src/Memory/Customizers/BasicMemory.o

# target to build an object file
src/Memory/Customizers/BasicMemory.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/Customizers/BasicMemory.cpp.o
.PHONY : src/Memory/Customizers/BasicMemory.cpp.o

src/Memory/Customizers/BasicMemory.i: src/Memory/Customizers/BasicMemory.cpp.i
.PHONY : src/Memory/Customizers/BasicMemory.i

# target to preprocess a source file
src/Memory/Customizers/BasicMemory.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/Customizers/BasicMemory.cpp.i
.PHONY : src/Memory/Customizers/BasicMemory.cpp.i

src/Memory/Customizers/BasicMemory.s: src/Memory/Customizers/BasicMemory.cpp.s
.PHONY : src/Memory/Customizers/BasicMemory.s

# target to generate assembly for a file
src/Memory/Customizers/BasicMemory.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/Customizers/BasicMemory.cpp.s
.PHONY : src/Memory/Customizers/BasicMemory.cpp.s

src/Memory/Customizers/DefaultERam.o: src/Memory/Customizers/DefaultERam.cpp.o
.PHONY : src/Memory/Customizers/DefaultERam.o

# target to build an object file
src/Memory/Customizers/DefaultERam.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/Customizers/DefaultERam.cpp.o
.PHONY : src/Memory/Customizers/DefaultERam.cpp.o

src/Memory/Customizers/DefaultERam.i: src/Memory/Customizers/DefaultERam.cpp.i
.PHONY : src/Memory/Customizers/DefaultERam.i

# target to preprocess a source file
src/Memory/Customizers/DefaultERam.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/Customizers/DefaultERam.cpp.i
.PHONY : src/Memory/Customizers/DefaultERam.cpp.i

src/Memory/Customizers/DefaultERam.s: src/Memory/Customizers/DefaultERam.cpp.s
.PHONY : src/Memory/Customizers/DefaultERam.s

# target to generate assembly for a file
src/Memory/Customizers/DefaultERam.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/Customizers/DefaultERam.cpp.s
.PHONY : src/Memory/Customizers/DefaultERam.cpp.s

src/Memory/Customizers/DefaultRom.o: src/Memory/Customizers/DefaultRom.cpp.o
.PHONY : src/Memory/Customizers/DefaultRom.o

# target to build an object file
src/Memory/Customizers/DefaultRom.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/Customizers/DefaultRom.cpp.o
.PHONY : src/Memory/Customizers/DefaultRom.cpp.o

src/Memory/Customizers/DefaultRom.i: src/Memory/Customizers/DefaultRom.cpp.i
.PHONY : src/Memory/Customizers/DefaultRom.i

# target to preprocess a source file
src/Memory/Customizers/DefaultRom.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/Customizers/DefaultRom.cpp.i
.PHONY : src/Memory/Customizers/DefaultRom.cpp.i

src/Memory/Customizers/DefaultRom.s: src/Memory/Customizers/DefaultRom.cpp.s
.PHONY : src/Memory/Customizers/DefaultRom.s

# target to generate assembly for a file
src/Memory/Customizers/DefaultRom.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/Customizers/DefaultRom.cpp.s
.PHONY : src/Memory/Customizers/DefaultRom.cpp.s

src/Memory/Customizers/EchoRam.o: src/Memory/Customizers/EchoRam.cpp.o
.PHONY : src/Memory/Customizers/EchoRam.o

# target to build an object file
src/Memory/Customizers/EchoRam.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/Customizers/EchoRam.cpp.o
.PHONY : src/Memory/Customizers/EchoRam.cpp.o

src/Memory/Customizers/EchoRam.i: src/Memory/Customizers/EchoRam.cpp.i
.PHONY : src/Memory/Customizers/EchoRam.i

# target to preprocess a source file
src/Memory/Customizers/EchoRam.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/Customizers/EchoRam.cpp.i
.PHONY : src/Memory/Customizers/EchoRam.cpp.i

src/Memory/Customizers/EchoRam.s: src/Memory/Customizers/EchoRam.cpp.s
.PHONY : src/Memory/Customizers/EchoRam.s

# target to generate assembly for a file
src/Memory/Customizers/EchoRam.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/Customizers/EchoRam.cpp.s
.PHONY : src/Memory/Customizers/EchoRam.cpp.s

src/Memory/Customizers/IOMemory.o: src/Memory/Customizers/IOMemory.cpp.o
.PHONY : src/Memory/Customizers/IOMemory.o

# target to build an object file
src/Memory/Customizers/IOMemory.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/Customizers/IOMemory.cpp.o
.PHONY : src/Memory/Customizers/IOMemory.cpp.o

src/Memory/Customizers/IOMemory.i: src/Memory/Customizers/IOMemory.cpp.i
.PHONY : src/Memory/Customizers/IOMemory.i

# target to preprocess a source file
src/Memory/Customizers/IOMemory.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/Customizers/IOMemory.cpp.i
.PHONY : src/Memory/Customizers/IOMemory.cpp.i

src/Memory/Customizers/IOMemory.s: src/Memory/Customizers/IOMemory.cpp.s
.PHONY : src/Memory/Customizers/IOMemory.s

# target to generate assembly for a file
src/Memory/Customizers/IOMemory.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/Customizers/IOMemory.cpp.s
.PHONY : src/Memory/Customizers/IOMemory.cpp.s

src/Memory/Customizers/VRam.o: src/Memory/Customizers/VRam.cpp.o
.PHONY : src/Memory/Customizers/VRam.o

# target to build an object file
src/Memory/Customizers/VRam.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/Customizers/VRam.cpp.o
.PHONY : src/Memory/Customizers/VRam.cpp.o

src/Memory/Customizers/VRam.i: src/Memory/Customizers/VRam.cpp.i
.PHONY : src/Memory/Customizers/VRam.i

# target to preprocess a source file
src/Memory/Customizers/VRam.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/Customizers/VRam.cpp.i
.PHONY : src/Memory/Customizers/VRam.cpp.i

src/Memory/Customizers/VRam.s: src/Memory/Customizers/VRam.cpp.s
.PHONY : src/Memory/Customizers/VRam.s

# target to generate assembly for a file
src/Memory/Customizers/VRam.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/Customizers/VRam.cpp.s
.PHONY : src/Memory/Customizers/VRam.cpp.s

src/Memory/Memory.o: src/Memory/Memory.cpp.o
.PHONY : src/Memory/Memory.o

# target to build an object file
src/Memory/Memory.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/Memory.cpp.o
.PHONY : src/Memory/Memory.cpp.o

src/Memory/Memory.i: src/Memory/Memory.cpp.i
.PHONY : src/Memory/Memory.i

# target to preprocess a source file
src/Memory/Memory.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/Memory.cpp.i
.PHONY : src/Memory/Memory.cpp.i

src/Memory/Memory.s: src/Memory/Memory.cpp.s
.PHONY : src/Memory/Memory.s

# target to generate assembly for a file
src/Memory/Memory.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/Memory.cpp.s
.PHONY : src/Memory/Memory.cpp.s

src/Memory/MemoryCustomizer.o: src/Memory/MemoryCustomizer.cpp.o
.PHONY : src/Memory/MemoryCustomizer.o

# target to build an object file
src/Memory/MemoryCustomizer.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/MemoryCustomizer.cpp.o
.PHONY : src/Memory/MemoryCustomizer.cpp.o

src/Memory/MemoryCustomizer.i: src/Memory/MemoryCustomizer.cpp.i
.PHONY : src/Memory/MemoryCustomizer.i

# target to preprocess a source file
src/Memory/MemoryCustomizer.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/MemoryCustomizer.cpp.i
.PHONY : src/Memory/MemoryCustomizer.cpp.i

src/Memory/MemoryCustomizer.s: src/Memory/MemoryCustomizer.cpp.s
.PHONY : src/Memory/MemoryCustomizer.s

# target to generate assembly for a file
src/Memory/MemoryCustomizer.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/MemoryCustomizer.cpp.s
.PHONY : src/Memory/MemoryCustomizer.cpp.s

src/Memory/MemoryLoader.o: src/Memory/MemoryLoader.cpp.o
.PHONY : src/Memory/MemoryLoader.o

# target to build an object file
src/Memory/MemoryLoader.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/MemoryLoader.cpp.o
.PHONY : src/Memory/MemoryLoader.cpp.o

src/Memory/MemoryLoader.i: src/Memory/MemoryLoader.cpp.i
.PHONY : src/Memory/MemoryLoader.i

# target to preprocess a source file
src/Memory/MemoryLoader.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/MemoryLoader.cpp.i
.PHONY : src/Memory/MemoryLoader.cpp.i

src/Memory/MemoryLoader.s: src/Memory/MemoryLoader.cpp.s
.PHONY : src/Memory/MemoryLoader.s

# target to generate assembly for a file
src/Memory/MemoryLoader.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/MemoryLoader.cpp.s
.PHONY : src/Memory/MemoryLoader.cpp.s

src/gameboy.o: src/gameboy.cpp.o
.PHONY : src/gameboy.o

# target to build an object file
src/gameboy.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/gameboy.cpp.o
.PHONY : src/gameboy.cpp.o

src/gameboy.i: src/gameboy.cpp.i
.PHONY : src/gameboy.i

# target to preprocess a source file
src/gameboy.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/gameboy.cpp.i
.PHONY : src/gameboy.cpp.i

src/gameboy.s: src/gameboy.cpp.s
.PHONY : src/gameboy.s

# target to generate assembly for a file
src/gameboy.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/gameboy.cpp.s
.PHONY : src/gameboy.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... gameboy"
	@echo "... rebuild_cache"
	@echo "... src/Common/FileUtils.o"
	@echo "... src/Common/FileUtils.i"
	@echo "... src/Common/FileUtils.s"
	@echo "... src/Cpu/Z80InstructionSet.o"
	@echo "... src/Cpu/Z80InstructionSet.i"
	@echo "... src/Cpu/Z80InstructionSet.s"
	@echo "... src/Memory/CartridgeHeader.o"
	@echo "... src/Memory/CartridgeHeader.i"
	@echo "... src/Memory/CartridgeHeader.s"
	@echo "... src/Memory/Customizers/BasicMemory.o"
	@echo "... src/Memory/Customizers/BasicMemory.i"
	@echo "... src/Memory/Customizers/BasicMemory.s"
	@echo "... src/Memory/Customizers/DefaultERam.o"
	@echo "... src/Memory/Customizers/DefaultERam.i"
	@echo "... src/Memory/Customizers/DefaultERam.s"
	@echo "... src/Memory/Customizers/DefaultRom.o"
	@echo "... src/Memory/Customizers/DefaultRom.i"
	@echo "... src/Memory/Customizers/DefaultRom.s"
	@echo "... src/Memory/Customizers/EchoRam.o"
	@echo "... src/Memory/Customizers/EchoRam.i"
	@echo "... src/Memory/Customizers/EchoRam.s"
	@echo "... src/Memory/Customizers/IOMemory.o"
	@echo "... src/Memory/Customizers/IOMemory.i"
	@echo "... src/Memory/Customizers/IOMemory.s"
	@echo "... src/Memory/Customizers/VRam.o"
	@echo "... src/Memory/Customizers/VRam.i"
	@echo "... src/Memory/Customizers/VRam.s"
	@echo "... src/Memory/Memory.o"
	@echo "... src/Memory/Memory.i"
	@echo "... src/Memory/Memory.s"
	@echo "... src/Memory/MemoryCustomizer.o"
	@echo "... src/Memory/MemoryCustomizer.i"
	@echo "... src/Memory/MemoryCustomizer.s"
	@echo "... src/Memory/MemoryLoader.o"
	@echo "... src/Memory/MemoryLoader.i"
	@echo "... src/Memory/MemoryLoader.s"
	@echo "... src/gameboy.o"
	@echo "... src/gameboy.i"
	@echo "... src/gameboy.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

