# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/michael/Dropbox/gameboyC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/michael/Dropbox/gameboyC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michael/Dropbox/gameboyC/CMakeFiles /home/michael/Dropbox/gameboyC/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michael/Dropbox/gameboyC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gameboy

# Build rule for target.
gameboy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gameboy
.PHONY : gameboy

# fast build rule for target.
gameboy/fast:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/build
.PHONY : gameboy/fast

src/Cartridge/CartridgeHeader.o: src/Cartridge/CartridgeHeader.cpp.o
.PHONY : src/Cartridge/CartridgeHeader.o

# target to build an object file
src/Cartridge/CartridgeHeader.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Cartridge/CartridgeHeader.cpp.o
.PHONY : src/Cartridge/CartridgeHeader.cpp.o

src/Cartridge/CartridgeHeader.i: src/Cartridge/CartridgeHeader.cpp.i
.PHONY : src/Cartridge/CartridgeHeader.i

# target to preprocess a source file
src/Cartridge/CartridgeHeader.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Cartridge/CartridgeHeader.cpp.i
.PHONY : src/Cartridge/CartridgeHeader.cpp.i

src/Cartridge/CartridgeHeader.s: src/Cartridge/CartridgeHeader.cpp.s
.PHONY : src/Cartridge/CartridgeHeader.s

# target to generate assembly for a file
src/Cartridge/CartridgeHeader.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Cartridge/CartridgeHeader.cpp.s
.PHONY : src/Cartridge/CartridgeHeader.cpp.s

src/Cartridge/CartridgeLoader.o: src/Cartridge/CartridgeLoader.cpp.o
.PHONY : src/Cartridge/CartridgeLoader.o

# target to build an object file
src/Cartridge/CartridgeLoader.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Cartridge/CartridgeLoader.cpp.o
.PHONY : src/Cartridge/CartridgeLoader.cpp.o

src/Cartridge/CartridgeLoader.i: src/Cartridge/CartridgeLoader.cpp.i
.PHONY : src/Cartridge/CartridgeLoader.i

# target to preprocess a source file
src/Cartridge/CartridgeLoader.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Cartridge/CartridgeLoader.cpp.i
.PHONY : src/Cartridge/CartridgeLoader.cpp.i

src/Cartridge/CartridgeLoader.s: src/Cartridge/CartridgeLoader.cpp.s
.PHONY : src/Cartridge/CartridgeLoader.s

# target to generate assembly for a file
src/Cartridge/CartridgeLoader.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Cartridge/CartridgeLoader.cpp.s
.PHONY : src/Cartridge/CartridgeLoader.cpp.s

src/Cartridge/RomCartridge.o: src/Cartridge/RomCartridge.cpp.o
.PHONY : src/Cartridge/RomCartridge.o

# target to build an object file
src/Cartridge/RomCartridge.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Cartridge/RomCartridge.cpp.o
.PHONY : src/Cartridge/RomCartridge.cpp.o

src/Cartridge/RomCartridge.i: src/Cartridge/RomCartridge.cpp.i
.PHONY : src/Cartridge/RomCartridge.i

# target to preprocess a source file
src/Cartridge/RomCartridge.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Cartridge/RomCartridge.cpp.i
.PHONY : src/Cartridge/RomCartridge.cpp.i

src/Cartridge/RomCartridge.s: src/Cartridge/RomCartridge.cpp.s
.PHONY : src/Cartridge/RomCartridge.s

# target to generate assembly for a file
src/Cartridge/RomCartridge.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Cartridge/RomCartridge.cpp.s
.PHONY : src/Cartridge/RomCartridge.cpp.s

src/Common/FileUtils.o: src/Common/FileUtils.cpp.o
.PHONY : src/Common/FileUtils.o

# target to build an object file
src/Common/FileUtils.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Common/FileUtils.cpp.o
.PHONY : src/Common/FileUtils.cpp.o

src/Common/FileUtils.i: src/Common/FileUtils.cpp.i
.PHONY : src/Common/FileUtils.i

# target to preprocess a source file
src/Common/FileUtils.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Common/FileUtils.cpp.i
.PHONY : src/Common/FileUtils.cpp.i

src/Common/FileUtils.s: src/Common/FileUtils.cpp.s
.PHONY : src/Common/FileUtils.s

# target to generate assembly for a file
src/Common/FileUtils.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Common/FileUtils.cpp.s
.PHONY : src/Common/FileUtils.cpp.s

src/Cpu/Z80InstructionSet.o: src/Cpu/Z80InstructionSet.cpp.o
.PHONY : src/Cpu/Z80InstructionSet.o

# target to build an object file
src/Cpu/Z80InstructionSet.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Cpu/Z80InstructionSet.cpp.o
.PHONY : src/Cpu/Z80InstructionSet.cpp.o

src/Cpu/Z80InstructionSet.i: src/Cpu/Z80InstructionSet.cpp.i
.PHONY : src/Cpu/Z80InstructionSet.i

# target to preprocess a source file
src/Cpu/Z80InstructionSet.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Cpu/Z80InstructionSet.cpp.i
.PHONY : src/Cpu/Z80InstructionSet.cpp.i

src/Cpu/Z80InstructionSet.s: src/Cpu/Z80InstructionSet.cpp.s
.PHONY : src/Cpu/Z80InstructionSet.s

# target to generate assembly for a file
src/Cpu/Z80InstructionSet.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Cpu/Z80InstructionSet.cpp.s
.PHONY : src/Cpu/Z80InstructionSet.cpp.s

src/Memory/mbc1Memory.o: src/Memory/mbc1Memory.cpp.o
.PHONY : src/Memory/mbc1Memory.o

# target to build an object file
src/Memory/mbc1Memory.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/mbc1Memory.cpp.o
.PHONY : src/Memory/mbc1Memory.cpp.o

src/Memory/mbc1Memory.i: src/Memory/mbc1Memory.cpp.i
.PHONY : src/Memory/mbc1Memory.i

# target to preprocess a source file
src/Memory/mbc1Memory.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/mbc1Memory.cpp.i
.PHONY : src/Memory/mbc1Memory.cpp.i

src/Memory/mbc1Memory.s: src/Memory/mbc1Memory.cpp.s
.PHONY : src/Memory/mbc1Memory.s

# target to generate assembly for a file
src/Memory/mbc1Memory.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/mbc1Memory.cpp.s
.PHONY : src/Memory/mbc1Memory.cpp.s

src/Memory/mbc2Memory.o: src/Memory/mbc2Memory.cpp.o
.PHONY : src/Memory/mbc2Memory.o

# target to build an object file
src/Memory/mbc2Memory.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/mbc2Memory.cpp.o
.PHONY : src/Memory/mbc2Memory.cpp.o

src/Memory/mbc2Memory.i: src/Memory/mbc2Memory.cpp.i
.PHONY : src/Memory/mbc2Memory.i

# target to preprocess a source file
src/Memory/mbc2Memory.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/mbc2Memory.cpp.i
.PHONY : src/Memory/mbc2Memory.cpp.i

src/Memory/mbc2Memory.s: src/Memory/mbc2Memory.cpp.s
.PHONY : src/Memory/mbc2Memory.s

# target to generate assembly for a file
src/Memory/mbc2Memory.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/mbc2Memory.cpp.s
.PHONY : src/Memory/mbc2Memory.cpp.s

src/Memory/mbc3Memory.o: src/Memory/mbc3Memory.cpp.o
.PHONY : src/Memory/mbc3Memory.o

# target to build an object file
src/Memory/mbc3Memory.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/mbc3Memory.cpp.o
.PHONY : src/Memory/mbc3Memory.cpp.o

src/Memory/mbc3Memory.i: src/Memory/mbc3Memory.cpp.i
.PHONY : src/Memory/mbc3Memory.i

# target to preprocess a source file
src/Memory/mbc3Memory.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/mbc3Memory.cpp.i
.PHONY : src/Memory/mbc3Memory.cpp.i

src/Memory/mbc3Memory.s: src/Memory/mbc3Memory.cpp.s
.PHONY : src/Memory/mbc3Memory.s

# target to generate assembly for a file
src/Memory/mbc3Memory.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/mbc3Memory.cpp.s
.PHONY : src/Memory/mbc3Memory.cpp.s

src/Memory/mbc5Memory.o: src/Memory/mbc5Memory.cpp.o
.PHONY : src/Memory/mbc5Memory.o

# target to build an object file
src/Memory/mbc5Memory.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/mbc5Memory.cpp.o
.PHONY : src/Memory/mbc5Memory.cpp.o

src/Memory/mbc5Memory.i: src/Memory/mbc5Memory.cpp.i
.PHONY : src/Memory/mbc5Memory.i

# target to preprocess a source file
src/Memory/mbc5Memory.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/mbc5Memory.cpp.i
.PHONY : src/Memory/mbc5Memory.cpp.i

src/Memory/mbc5Memory.s: src/Memory/mbc5Memory.cpp.s
.PHONY : src/Memory/mbc5Memory.s

# target to generate assembly for a file
src/Memory/mbc5Memory.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/mbc5Memory.cpp.s
.PHONY : src/Memory/mbc5Memory.cpp.s

src/Memory/memory.o: src/Memory/memory.cpp.o
.PHONY : src/Memory/memory.o

# target to build an object file
src/Memory/memory.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/memory.cpp.o
.PHONY : src/Memory/memory.cpp.o

src/Memory/memory.i: src/Memory/memory.cpp.i
.PHONY : src/Memory/memory.i

# target to preprocess a source file
src/Memory/memory.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/memory.cpp.i
.PHONY : src/Memory/memory.cpp.i

src/Memory/memory.s: src/Memory/memory.cpp.s
.PHONY : src/Memory/memory.s

# target to generate assembly for a file
src/Memory/memory.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/Memory/memory.cpp.s
.PHONY : src/Memory/memory.cpp.s

src/gameboy.o: src/gameboy.cpp.o
.PHONY : src/gameboy.o

# target to build an object file
src/gameboy.cpp.o:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/gameboy.cpp.o
.PHONY : src/gameboy.cpp.o

src/gameboy.i: src/gameboy.cpp.i
.PHONY : src/gameboy.i

# target to preprocess a source file
src/gameboy.cpp.i:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/gameboy.cpp.i
.PHONY : src/gameboy.cpp.i

src/gameboy.s: src/gameboy.cpp.s
.PHONY : src/gameboy.s

# target to generate assembly for a file
src/gameboy.cpp.s:
	$(MAKE) -f CMakeFiles/gameboy.dir/build.make CMakeFiles/gameboy.dir/src/gameboy.cpp.s
.PHONY : src/gameboy.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... gameboy"
	@echo "... rebuild_cache"
	@echo "... src/Cartridge/CartridgeHeader.o"
	@echo "... src/Cartridge/CartridgeHeader.i"
	@echo "... src/Cartridge/CartridgeHeader.s"
	@echo "... src/Cartridge/CartridgeLoader.o"
	@echo "... src/Cartridge/CartridgeLoader.i"
	@echo "... src/Cartridge/CartridgeLoader.s"
	@echo "... src/Cartridge/RomCartridge.o"
	@echo "... src/Cartridge/RomCartridge.i"
	@echo "... src/Cartridge/RomCartridge.s"
	@echo "... src/Common/FileUtils.o"
	@echo "... src/Common/FileUtils.i"
	@echo "... src/Common/FileUtils.s"
	@echo "... src/Cpu/Z80InstructionSet.o"
	@echo "... src/Cpu/Z80InstructionSet.i"
	@echo "... src/Cpu/Z80InstructionSet.s"
	@echo "... src/Memory/mbc1Memory.o"
	@echo "... src/Memory/mbc1Memory.i"
	@echo "... src/Memory/mbc1Memory.s"
	@echo "... src/Memory/mbc2Memory.o"
	@echo "... src/Memory/mbc2Memory.i"
	@echo "... src/Memory/mbc2Memory.s"
	@echo "... src/Memory/mbc3Memory.o"
	@echo "... src/Memory/mbc3Memory.i"
	@echo "... src/Memory/mbc3Memory.s"
	@echo "... src/Memory/mbc5Memory.o"
	@echo "... src/Memory/mbc5Memory.i"
	@echo "... src/Memory/mbc5Memory.s"
	@echo "... src/Memory/memory.o"
	@echo "... src/Memory/memory.i"
	@echo "... src/Memory/memory.s"
	@echo "... src/gameboy.o"
	@echo "... src/gameboy.i"
	@echo "... src/gameboy.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

